### ISSUE TITLE
Package Dependency Version Bump

### ISSUE THREAD

**Issue by AnthonyMDev** [Kitura/Kitura-StencilTemplateEngine#1]
The dependency on `Kitura-TemplateEngine` needs to be bumped to use `0.10.0`. I'm currently getting a dependency graph resolution error when attempting to include this package.

Thanks

**Comment by vadimeisenbergibm** [comment]
Done in https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/commit/cdbbb36e3763f8225bb320cbb494ea5aa49f5bf9
