### ISSUE TITLE
{{ block.super }} not working?

### ISSUE THREAD

**Issue by svanimpe** [Kitura/Kitura-StencilTemplateEngine#13]
Please see https://github.com/kylef/Stencil/issues/107

I am opening an issue here as the bug was reproducible for me, but unit tests show it is not an issue with Stencil.

**Comment by kylef** [comment]
@svanimpe just to check, you are running the 1.8.0 (https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/releases/tag/1.8.0) of  Kitura-StencilTemplateEngine and Stencil 0.8?

**Comment by svanimpe** [comment]
Indeed I am.

**Comment by vadimeisenbergibm** [comment]
@svanimpe please see my answer at kylef/Stencil#107 :  https://github.com/kylef/Stencil/issues/107#issuecomment-293365188

**Comment by svanimpe** [comment]
Right, that was the issue. Apologies for wasting your time with something this stupid. *facepalm*

**Comment by vadimeisenbergibm** [comment]
@svanimpe That's OK, no worries :)
