### ISSUE TITLE
Support for template files organized in directories

### ISSUE THREAD

**Issue by gmosx** [Kitura/Kitura-StencilTemplateEngine#14]
The current implementation does not support templates organized in directories,
e.g. the following doesn't work:

```
try response.render("accounts/account.stencil", context: context).end()
```

This is a serious limitation.

**Comment by vadimeisenbergibm** [comment]
@gmosx For me it works - please see the test in https://github.com/IBM-Swift/Kitura-Sample/pull/71

**Comment by gmosx** [comment]
After the related issue #16 was fixed I don't have any further problems.
