### ISSUE TITLE
Update to Stencil 0.9

### ISSUE THREAD

**Issue by svanimpe** [Kitura/Kitura-StencilTemplateEngine#15]
https://github.com/kylef/Stencil/releases/tag/0.9.0

`Package.swift` currently requires 0.8. I had to add an explicit dependency on Stencil 0.9 to my project to use the newer version.

**Comment by vadimeisenbergibm** [comment]
Fixed in https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/tree/1.8.1
