### ISSUE TITLE
Allow template filenames with different file extensions

### ISSUE THREAD

**Issue by jasonwoodland** [Kitura/Kitura-StencilTemplateEngine#19]
Would it be possible to allow template filenames with an extension other than .stencil?
Even the [stencil docs](http://stencil.fuller.li/en/latest/templates.html#template-inheritance) make use of a .html extension.

To temporarily achieve this myself, I manually added StencilTemplateEngine.swift to my project and changed: `public var fileExtension: String { return "stencil" }` 
to: `public var fileExtension: String = "stencil"`
Then I could change the extension myself in main.swift:
```
let templateEngine = StencilTemplateEngine()
templateEngine.fileExtension = "html"
```

PS. I also tried doing this using an extension:
```
public extension StencilTemplateEngine {
    public var fileExtension: String { return "html" }
}
```
Even though StencilTemplateEngine().fileExtension returned "html" it didn't work for whatever reason.

**Comment by vadimeisenbergibm** [comment]
@jasonwoodland `fileExtension` is used when you do not specify file extension for your template in `response.render` and you register your template engine as a default. In all other cases, you just specify file extension of your template, be it `.stencil` or `.html`.

For example:
```
router.setDefault(templateEngine: StencilTemplateEngine())
response.render("document", context: context) // document.stencil will be rendered since 
                                              // StencilTemplateEngine is the default template engine
response.render("document.html", context: context) // document.html will be rendered
```

**Comment by jasonwoodland** [comment]
Yeah I thought this is how it would behave, so I tried again:

Sources/main.swift:
```
import Kitura
import KituraStencil

let router = Router()

router.add(templateEngine: StencilTemplateEngine())
router.setDefault(templateEngine: StencilTemplateEngine())

router.get("/test") { request, response, next in
	let context: [String: Any] = [
		"test": "hello"
	]
	try response.render("test.html", context: context).end()
}


// Add an HTTP server and connect it to the router
Kitura.addHTTPServer(onPort: 8080, with: router)

// Start the Kitura runloop (this call never returns)
Kitura.run()
```

tree:
```
.
├── Package.pins
├── Package.swift
├── Sources
│   └── main.swift
├── Tests
└── Views
    └── test.html
```
And I tried:
```
% curl localhost:8080/test
Cannot GET /test.
% 
```

Package.swift:
```
// swift-tools-version:3.1

import PackageDescription

let package = Package(
    name: "Framework",
    dependencies: [
        .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 7),
        .Package(url: "https://github.com/IBM-Swift/Kitura-StencilTemplateEngine.git", majorVersion: 1, minor: 8)
    ]
)
```

**Comment by vadimeisenbergibm** [comment]
@jasonwoodland You are right, my fault. I forgot that you have to specify "html" in `forFileExtensions` parameter when you add your template engine:
```
router.add(templateEngine: StencilTemplateEngine(extension: _extension),
                   forFileExtensions: ["html"])
```
Added this line and a test case in
https://github.com/IBM-Swift/Kitura-Sample/blob/issue_19/Sources/KituraSampleRouter/RouterCreator.swift#L163, in  https://github.com/IBM-Swift/Kitura-Sample/issues/73 .

**Comment by jasonwoodland** [comment]
`forFileExtensions:` works for me. I still have to specify `.html` but I'm happy with this. Thanks
