### ISSUE TITLE
Update to Stencil 0.10

### ISSUE THREAD

**Issue by svanimpe** [Kitura/Kitura-StencilTemplateEngine#21]
This version fixes an important bug for me, so it would be nice if Kitura-StencilTemplateEngine used it by default (so I don't have to add an additional dependency).

**Comment by seabaylea** [comment]
@christiancompton can you take a look at this?

**Comment by christiancompton** [comment]
PR: https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/pull/22 

I will tag this version `1.8.4` on the merge commit.

**Comment by christiancompton** [comment]
Closing as complete. This change is available in the [1.8.4 release](https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/releases/tag/1.8.4).
