### ISSUE TITLE
Build fails when code coverage is enabled

### ISSUE THREAD

**Issue by svanimpe** [Kitura/Kitura-StencilTemplateEngine#31]
Steps to reproduce:

- Clone https://github.com/IBM-Swift/Kitura-Sample
- Generate an Xcode project
- Enable code coverage for **KituraSampleRouter** in Edit Scheme > Test > Options.
- Test project

This fails with the following error:

```
Undefined symbols for architecture x86_64:
  "static (extension in Foundation):Swift.String._unconditionallyBridgeFromObjectiveC(__ObjC.NSString?) -> Swift.String", referenced from:
      __C.StringTransform.rawValue.getter : Swift.String in KituraStencilTemplateEngine.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Adding an explicit `import Foundation` to **KituraStencilTemplateEngine.swift** fixes it.

**Comment by ianpartridge** [comment]
Tagged as https://github.com/IBM-Swift/Kitura-StencilTemplateEngine/releases/tag/1.9.1 - thanks @svanimpe
