### ISSUE TITLE
Is it possible to write own operators and for-loop with extension?

### ISSUE THREAD

**Issue by diuming** [Kitura/Kitura-StencilTemplateEngine#42]
I want to write my own for-loop and tags. could you give me advice? thanks!
```
let ext = Extension()
...
router.setDefault(templateEngine: StencileTemplateEngine(extension: ext))
```
is it possible to write own for-loop {% for row in 0`..<`count %} with extension like swift?
is it possible to write operators (+, -, *, /, %} tag with extension? 

access array in nested for-loop with operators(+, -, *, /, %)?
---
```
{% for row in 0..<9 %}
    {% for column in 0..<9 %}
         {% set index = row (+, -, *, /, %) column %}
         {{ array[index].attribute.value }}
    {% endfor %}
{% endfor %}
```

**Comment by DunnCoding** [comment]
Hi @diuming 

I don't think it's possible to create your own `for` tag in Stencil like that. 

You can however create your own filters, and add them to the StencilTemplateEngine as an extension. 

## 1. Creating a for-loop filter similar to the for value in range loop in Swift

EDIT: It seems like Stencil does support looping over ranges: 
```
{% for i in 1...array.count %}
    <li>{{ i }}</li>
  {% endfor %}
```
I found this when reading more into how Stencil defines their `for` tags, but you can find the documentation [here](http://stencil.fuller.li/en/latest/builtins.html#for)

Is that what you are looking for? 

## 2. Creating an operator filter to enable basic mathematical operations

I'm not sure if you're wanting to create a filter that will allow you to perform any operation you want or not? 

If you wanted you could create a filter for each operation, or create a single filter that will handle all the operations for you. Something like this:

```swift
ext.registerFilter("operation") { (value: Any?, arguments: [Any?]) in
    if arguments.count != 2 {
        throw TemplateSyntaxError("The operation tag must only contain 2 arguments")
    }
    
    guard let num = value as? Int else {
        throw TemplateSyntaxError("Value provided must be an integer for operators to be called on it.")
    }
    
    guard let operand = arguments[1] as? Int else {
        throw TemplateSyntaxError("operation tag must be called with integer as the last argument.")
    }
    
    guard let `operator` = arguments[0] as? String else {
        throw TemplateSyntaxError("operation tag must be called with a String as the first argument")
    }
    
    switch `operator` {
    case "+":
        return num + operand
    case "*":
        return num * operand
    case "/":
        return num / operand
    case "-":
        return num - operand
    case "%":
        return num % operand
    default:
        throw TemplateSyntaxError("Invalid operation performed.")
    }
}
```

Then in your Stencil file you would use this filter like so: 
```
{{ 19|operation:"+", 8 }}
```

## 3. Bringing it all together

To do what you are looking to do based on your Stencil:

```
{% for row in 0..<9 %}
    {% for column in 0..<9 %}
         {% set index = row (+, -, *, /, %) column %}
         {{ array[index].attribute.value }}
    {% endfor %}
{% endfor %}
```

You may need to create a custom filter for that by combining the above examples I've provided but you can find more information about Custom filters in [Stencils Documentation](http://stencil.fuller.li/en/latest/custom-template-tags-and-filters.html)

If you need any more help please feel free to ask :)

**Comment by diuming** [comment]
@ddunn2 thank you so much for replying.
1. it is not convenient to access array. because array is zero-based. but anyway, thanks
2. it's a good example. I like it. thanks.
3. as you example `{{ 19|operation:"+", 8 }}`.
   Do it correct way to access element in array with nested {{ `{{ do something }}` }}?. please  take a look below.
   {{ myArray[`{{ 19|operation:"+", 8 }}`].attribute.value }}

**Comment by DunnCoding** [comment]
@diuming Don't worry about it! 

What is it you are trying to do? Something like what you are doing might be better in your server code rather than your rendering logic. 

You could do something like this though: 

```swift
func performOperation(_ firstOperand: Int, _ operator: String, _ secondOperand: Int) throws -> Int {
    
    switch `operator` {
    case "+":
        return firstOperand + secondOperand
    case "*":
        return firstOperand * secondOperand
    case "/":
        return firstOperand / secondOperand
    case "-":
        return firstOperand - secondOperand
    case "%":
        return firstOperand % secondOperand
    default:
        throw TemplateSyntaxError("Invalid operation performed.")
    }
}

ext.registerFilter("buildContext") { (value: Any?, arguments: [Any?]) in
    guard let array = value as? [Any?] else {
        throw TemplateSyntaxError("Value must be an array.")
    }
    
    guard let `operator` = arguments[0] as? String else {
        throw TemplateSyntaxError("First argument must be a String.");
    }
    
    var resultArray: [Any?] = []
    for row in 0..<9 {
        for column in 0..<9 {
            do {
                let index = try performOperation(row, `operator`, column)
                if index < array.count {
                    resultArray.append(array[index].attribute.value)
                } else {
                    continue
                }
            } catch {
                throw TemplateSyntaxError(error.localizedDescription);
            }
        }
    }
    return resultArray;
}
```

Then you can use this in your stencil file like this: 
```
{{ array|buildContext:"+" }}
```

Then it should build the context you want Stencil to render. 

I can't seem to find a way to access an array within the Stencil file itself, so I'm unsure as to whether this is possible. 

I hope this helps!

**Comment by diuming** [comment]
@ddunn2 thank you so much.
it is a good solution I learned.
