### ISSUE TITLE
Simultaneous accesses ... Fatal access conflict detected

### ISSUE THREAD

**Issue by AkshayNG** [Kitura/Kitura-StencilTemplateEngine#43]
Running `swift package generate-xcodeproj` after updating package.swift file gives an error:

> Simultaneous accesses to 0x7fe41a769f78, but modification requires exclusive access.
> Previous access (a modification) started at swift-package`CacheableSequence.subscript.getter + 1489 (0x102f60e31).
> Current access (a read) started at:
> .
> .
> .
> .
> Fatal access conflict detected.
> Abort trap: 6

**package.swift:**

<img width="993" alt="Screenshot 2019-04-07 at 5 29 19 PM" src="https://user-images.githubusercontent.com/15035623/55683199-c21b2b80-595a-11e9-86c5-d6b5d58ba870.png">

**Comment by DunnCoding** [comment]
@AkshayNG The reason for this error is you’ve named your project directory `Stencil` which is also the name of one of the dependencies which `KituraStencil` relies on. 
SPM doesn’t handle this very well, to resolve this issue change your project name to something else :slightly_smiling_face:.

**Comment by AkshayNG** [comment]
@ddunn2 You are right. New project with name as 'StencilDemo' just worked fine. Thanks 👍:)
