### ISSUE TITLE
Stencil does not render

### ISSUE THREAD

**Issue by yo1995** [Kitura/Kitura-StencilTemplateEngine#45]
Hi,

I'm new to Kitura, and was playing around with Stencil to see its template capability.
However, when I followed the guide in this repo, although the stencil file is displayed, the template does not render according to the context. That is to say: what I see on the page is:

```html
There are {{ articles.count }} articles. 
{% for article in articles %} - {{ article.title }} written by . 
{% endfor %}
```

I wonder how I should fix this problem. 🤔 

Thanks,

System version: Ubuntu 16.04.6
Kitura version: latest
StencilTemplateEngine: 1.11.1
Dependencies: `.target(name: "Application", dependencies: ["KituraStencil", "Kitura", "HeliumLogger", "KituraMarkdown"]),`

**Comment by yo1995** [comment]
Despite no style-sheet for markdown renderer, it still works. 

In contrast, Stencil does not render the context parameter passed into it. 

I tried with multiple input data, and it does not work...

Any help is appreciated! 🙏

**Comment by DunnCoding** [comment]
Hey @yo1995 

Can you share your stencil route? That is, the route where you're trying to render your Stencil file? 

In the meantime I'll attempt to recreate your issue :)

**Comment by yo1995** [comment]
> Hey @yo1995
> 
> Can you share your stencil route? That is, the route where you're trying to render your Stencil file?
> 
> In the meantime I'll attempt to recreate your issue :)

Hi,
Thanks for you prompt reply! I'm doing some further experiments and will provide more details later. 😄 

Right now I found the template is partially rendered, and is investigating this issue.

**Comment by yo1995** [comment]
@ddunn2 @ianpartridge 

I found the issue. The problem comes from my template file. I edited it on a Windows machine, and forgot to check the line endings, which is then saved to `CRLF` by default. After cleaning those `\r` characters, the template file renders fine.

Is this an issue related to `Stencil` itself? Maybe I should create an issue in their repo. 🤔

**Comment by yo1995** [comment]
Close as the issue is solved.
