### ISSUE TITLE
The KituraStencil can't run in Xcode 11?

### ISSUE THREAD

**Issue by diuming** [Kitura/Kitura-StencilTemplateEngine#48]
Environment
---
OS: macOS 10.15.1
Kitura-StencilTemplateEngine: 1.11.0
Xcode: 11.2

Description
---
The Kitura-Stencil can't runs in Xcode 11, when I open a project by `Package.swift`.
but except 2  ways:
1) swift build and run in terminal.
2) swift package generate-xcodeproj and run in Xcode 11.

Could you give me any advice?
Thanks

code
---
```
func initializeSomeRoutes(app: App) {
    app.router.setDefault(templateEngine: StencilTemplateEngine())
    app.router.get("/demo") { (request, response, next) in
        do {
            let data: [String: Any] = ["name": "Allen", "age": 44]
            try response.render("demo.stencil", context: data)
        } catch {
            response.status(.internalServerError).send(error.localizedDescription)
        }
    }
}
```
error message
---
The operation couldn’t be completed. (KituraStencil.StencilTemplateEngineError error 1.)

**Comment by MadGeorge** [comment]
I have same issue. Just cloned my repo which which is works fin in production and got same error. 
Also StaticFileServer does not work as well. I got 404 for any file located in `/assets`. My setup is 
```
func postInit() throws {
    ...
    router.all("/assets", middleware: StaticFileServer(path: "Views/assets"))
```
