### ISSUE TITLE
Add support for {% include %} tag

### ISSUE THREAD

**Issue by gmosx** [Kitura/Kitura-StencilTemplateEngine#6]
Most probably a TemplateLoaded that loads from the Views directory (or the path of the TemplateEngine) bust be passed to the context or something like that.

**Comment by ianpartridge** [comment]
Thanks for suggesting this enhancement - it sounds like a useful feature to add. I'm afraid the IBM team are unlikely to be able to work on this in the short term, but we welcome patches!

**Comment by ianpartridge** [comment]
Closing because @vadimeisenbergibm fixed this in HEAD. Thanks!
